### ISSUE TITLE
I suggest to adding paging function.

### ISSUE THREAD

**Issue by 188007803** [tandg-digital/objection-filter#17] opened 2019-08-19 18:10 UTC
how about that:

in FilterQueryBuilder.js

```javascript
// 78+: 
page  = params.page || [];

// 88+:
 applyPage(page[0], page[1], this._builder);

// 612+: 
var applyPage = function applyPage(pageIndex, pageSize, builder) {
  if (pageIndex == null && pageSize == null){
    return builder;
  }
  pageIndex = ~~pageIndex || 0;
  pageSize  = ~~pageSize  || 10;
  builder.page(pageIndex, pageSize)
  return builder;
};
module.exports.applyPage = applyPage;
```

then, you can simply use paging:

```
{
      eager: {
            $where: {
                ....
            }
        },
        page: [1,3]
}

```

**Comment by jeff3yan** [comment] 2019-08-19 20:32
I'll have a think about it, but this will essentially be a duplicate of the limit/offset function.

For this type of functionality, I'd recommend extending it prior to injecting params into objection-filter. This reduces any duplicate functionality, which also reduces any test requirements.

You could have your own API/interface take the `page: [1, 3]` input parameter, then transform it to `limit` and `offset` in your handler.

**Comment by jeff3yan** [comment] 2019-08-20 22:08
Closing unless there's a clear benefit in implementing on top of the existing limit/offset.

**Closed by jeff3yan** 2019-08-20 22:08 UTC

**Comment by 188007803** [comment] 2019-08-21 06:16
'page' is not only means 'limit' and 'offset', in objection, it return {count, rows} , that's what I need.

**Comment by jeff3yan** [comment] 2019-08-21 19:27
I see what you mean. However I still feel that's outside the scope of objection-filter, and better suited to an application level implementation.

Especially if you want to inject { count, rows } information into the result set, by modifying the response body envelope. That wouldn't be difficult to do with result of objection-filter's `build()` method, and objection.js' [resultSize()](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#resultsize).

**Comment by jeff3yan** [comment] 2019-08-23 20:41
Another thing to note that I completely forgot, is that objection-filter will return a QueryBuilder from it's build() function.

You can call objection.js' `page()` function directly after for your desired result.
